---
title: Listen and Watch
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
defaults:
- scope:
    path: ''
    type: videos
  values:
    youtube: 
    artist: 
    layout: default
url: http://listenand.watch
permalink: pretty
exclude:
- "*.config"
- assets/src
- ".gitignore"
- Gulpfile.js
- node_modules
- package.json
- README*
- tools/
- webpack.config.js
